### ISSUE TITLE
Add documentation/features for security

### ISSUE THREAD

**Issue by ndarilek** [MiroHibler/meteor-mailchimp#22]
Not sure if I missed something obvious, but with this plus the mailchimp-lists package installed, as a non-logged-in user I can run:

    l = new MailChimpLists()
    l.refresh()
    l.lists()

in my Firebug console and get all sorts of juicy data about my lists, even if I'm not logged in.

Did I miss something in the docs about how to secure these methods from client-side access? My API keys are private but this still somehow manages to leak access to non-privileged users.

**Comment by MiroHibler** [comment]
Good point!

Let me dive into it and get back to you...

**Comment by ndarilek** [comment]
Maybe it'd be best to just make everything server-side and replace the
simple forms with longer examples. So the subscribe form would instead
be an example of a template calling a custom, server-side
subscribeToList method or something. I think that's the best solution,
barring some sort of method call firewall package that I haven't been
able to find.

I'll be moving the API key to the private settings namespace and moving
all the calls into methods shortly. The simple integrations you offer
are nice, but I think they make too much available on the client and
should probably be dropped or otherwise locked down.

**Comment by discdiver** [comment]
Is this still a concern? I wasn't able to replicate.

**Comment by MiroHibler** [comment]
More than a year passed since you opened this issue and only now I have some time to take care of it properly. Yet I just discovered that you're referring to [MailChimpLists](https://github.com/MiroHibler/meteor-mailchimp-lists) and not MailChimp (this repo), so I'm going to close this one and if you still have the same problem, please open an issue in [MailChimpLists](https://github.com/MiroHibler/meteor-mailchimp-lists) repo.

Thanks!
