### ISSUE TITLE
Updating settings.json from a form inside your app 

### ISSUE THREAD

**Issue by amazingBastard** [MiroHibler/meteor-mailchimp#27]
Hey,

Is there a way to change the mailchimp api key and list id in settings.json through a form that exists on the app? 

For example, if I have a subscribe form on my blog, and I can log in to the admin section and update the subscription form info through a cms. Any idea if that's possible somehow? Thanks.

**Comment by MiroHibler** [comment]
If you want to save the new credentials to settings.json - I don't think so.

But since you have a CMS, than you can save dynamic credentials in DB and read and pass them on each call. They will override the ones in settings.json. Just make a wrapper serverside (or both sides) and call them instead (without credentials!), read the credentials from DB within wrapper and then call the API.

**Comment by amazingBastard** [comment]
Thanks! I'll give this a try.
